version: '3.7'

services:

  apiserver:
    image: fonoster/fonos-ghauth:latest
    environment: 
      - CLIENT_ID
      - CLIENT_SECRET
      - CALLBACK_URL
    ports:
      - "3000:3000"
    volumes:
      - ${CONFIG}/config:/home/fonos/.fonos/config
  
